### ISSUE TITLE
pyicu/libICU error LEFontInstance can't be imported

### ISSUE THREAD

**Issue by n7s** [silnrsi/palaso-python#2]
While I was updating the toolchain I noticed that pyicu seems to have changed and causes the following error:

Traceback (most recent call last):
  File "/usr/bin/cmptxtrender", line 4, in <module>
    from palaso.font.shape import make_shaper
  File "/usr/lib/python2.7/dist-packages/palaso/font/shape.py", line 4, in <module>
    import palaso.font.icule as icule
  File "/usr/lib/python2.7/dist-packages/palaso/font/icule.py", line 1, in <module>
    from icu import LEFontInstance
ImportError: cannot import name LEFontInstance

The current bionic package is version 1.9.8-0ubuntu1 
Force-uninstalling that package and building from source from https://github.com/ovalhub/pyicu  seems to bring the same result.

**Comment by n7s** [comment]
LayoutEngine is deprecated http://userguide.icu-project.org/layoutengine.  Would https://github.com/harfbuzz/icu-le-hb provide what we need here?
